# This is a basic workflow to help you get started with Actions

name: Card Captor

# Controls when the workflow will run
on:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule: 
    - cron: '0 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent sa sequence of tasks that will be executed as part of the job
    steps:
      - id: repo1
        name: Repo Checkout
        uses: actions/checkout@v3

      - id: installation
        name: Python Setup & Packages Installation
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 pandas requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - id: python_start 
        name: python Excution
        run: python3 main.py
        shell: bash 

      - id: commit
        name: Commit files
        run:
          git config --local user.name actions-user

          git config --local user.email "actions@github.com"

          git add -A

          git commit -am "GH ACTION Headlines $(date)"

          git push origin main

        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}

          username: github-actions
